all: A2Q4.class hello

A2Q4.class: A2Q4.java
	javac A2Q4.java

hello:
	@echo [To run program, enter the following command (three arguments required):]
	@echo - java A2Q4 [name of first text file] [name of second text file] [join condition]
	@echo - example: java A2Q4 set1_left.txt set1_right.txt product_id 

