all: A3Q1.class hello

A3Q1.class: A3Q1.java
	javac A3Q1.java

hello:
	@echo [To run program, enter the following command (three arguments required):]
	@echo - java A3Q1 [name of first text file] [name of second text file] [join condition]
	@echo - example: java A3Q1 set1_left.txt set1_right.txt product_id 

